console.log(typeof 42)
console.log(typeof "Akhil")
console.log(typeof true)
console.log(typeof 'true')
console.log(typeof undeclaredVariables)
console.log(typeof null)
console.log(typeof new function(){})
console.log(typeof BigInt)
console.log(typeof NaN)
console.log(typeof Symbol())